### ISSUE TITLE
Error Messages with example: mesh strip

### ISSUE THREAD

**Issue by Beberger** [compas-dev/compas_fea#120]
Hello everyone,

I am using COMPAS FEA for my Master's Thesis and an error message occurs when I am running the example "mesh strip" in Rhino. Has somebody an idea where the errors come from?

best regrads
Ben

**The Error code is:**

`Message: Traceback (most recent call last):
  File "D:\Programme_Masterthesis\Anaconda3\lib\site-packages\compas\rpc\dispatcher.py", line 89, in _dispatch
    module = importlib.import_module(modulename)
  File "D:\Programme_Masterthesis\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Programme_Masterthesis\compas_fea-main\src\compas_fea\utilities\__init__.py", line 44, in <module>
    from .functions import (
  File "D:\Programme_Masterthesis\compas_fea-main\src\compas_fea\utilities\functions.py", line 5, in <module>
    from compas.datastructures import Mesh
  File "D:\Programme_Masterthesis\Anaconda3\lib\site-packages\compas\datastructures\__init__.py", line 203, in <module>
    from .network import *  # noqa: F401 E402 F403
  File "D:\Programme_Masterthesis\Anaconda3\lib\site-packages\compas\datastructures\network\__init__.py", line 5, in <module>
    from .core import *  # noqa: F401 F403
  File "D:\Programme_Masterthesis\Anaconda3\lib\site-packages\compas\datastructures\network\core\__init__.py", line 8, in <module>
    from .network import BaseNetwork  # noqa: F401
  File "D:\Programme_Masterthesis\Anaconda3\lib\site-packages\compas\datastructures\network\core\network.py", line 8, in <module>
    from compas.files import OBJ
  File "D:\Programme_Masterthesis\Anaconda3\lib\site-packages\compas\files\__init__.py", line 124, in <module>
    from .gltf import *  # noqa: F401 F403
  File "D:\Programme_Masterthesis\Anaconda3\lib\site-packages\compas\files\gltf\__init__.py", line 5, in <module>
    from .gltf import GLTF
  File "D:\Programme_Masterthesis\Anaconda3\lib\site-packages\compas\files\gltf\gltf.py", line 8, in <module>
    from compas.files.gltf.gltf_parser import GLTFParser
  File "D:\Programme_Masterthesis\Anaconda3\lib\site-packages\compas\files\gltf\gltf_parser.py", line 14, in <module>
    from compas.files.gltf.gltf_content import GLTFContent
  File "D:\Programme_Masterthesis\Anaconda3\lib\site-packages\compas\files\gltf\gltf_content.py", line 6, in <module>
    from compas.files.gltf.gltf_node import GLTFNode
  File "D:\Programme_Masterthesis\Anaconda3\lib\site-packages\compas\files\gltf\gltf_node.py", line 10, in <module>
    from compas.geometry import identity_matrix
  File "D:\Programme_Masterthesis\Anaconda3\lib\site-packages\compas\geometry\__init__.py", line 401, in <module>
    from .bbox import *  # noqa: F401 F403
  File "D:\Programme_Masterthesis\Anaconda3\lib\site-packages\compas\geometry\bbox\__init__.py", line 10, in <module>
    from .bbox_numpy import *  # noqa: F401 F403
  File "D:\Programme_Masterthesis\Anaconda3\lib\site-packages\compas\geometry\bbox\bbox_numpy.py", line 24, in <module>
    from compas.numerical import pca_numpy
  File "D:\Programme_Masterthesis\Anaconda3\lib\site-packages\compas\numerical\__init__.py", line 96, in <module>
    from .linalg import *  # noqa: F401 F403
  File "D:\Programme_Masterthesis\Anaconda3\lib\site-packages\compas\numerical\linalg.py", line 28, in <module>
    from scipy.sparse.linalg import factorized
  File "D:\Programme_Masterthesis\Anaconda3\lib\site-packages\scipy\sparse\linalg\__init__.py", line 114, in <module>
    from .eigen import *
  File "D:\Programme_Masterthesis\Anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\__init__.py", line 9, in <module>
    from .arpack import *
  File "D:\Programme_Masterthesis\Anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\__init__.py", line 20, in <module>
    from .arpack import *
  File "D:\Programme_Masterthesis\Anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 42, in <module>
    from . import _arpack
ImportError: DLL load failed while importing _arpack: Die angegebene Prozedur wurde nicht gefunden.

Traceback:
  line 345, in _proxy, "D:\Programme_Masterthesis\compas-main\src\compas\rpc\proxy.py"
  line 926, in plot_data, "D:\Programme_Masterthesis\compas_fea-main\src\compas_fea\cad\rhino.py"
  line 69, in <module>, "D:\Programme_Masterthesis\compas_fea-main\examples\mesh_strip_rhino.py"`

**The script I enter is:**

`
from compas_fea.cad import rhino
from compas_fea.structure import ElasticIsotropic
from compas_fea.structure import ElementProperties as Properties
from compas_fea.structure import GeneralDisplacement
from compas_fea.structure import GeneralStep
from compas_fea.structure import GravityLoad
from compas_fea.structure import PinnedDisplacement
from compas_fea.structure import RollerDisplacementX
from compas_fea.structure import ShellSection
from compas_fea.structure import Structure

# Author(s): Andrew Liew (github.com/andrewliew)

# Structure

mdl = Structure(name='mesh_strip', path='C:/Temp/')

# Elements

rhino.add_nodes_elements_from_layers(mdl, mesh_type='ShellElement', layers='elset_mesh')

# Sets

rhino.add_sets_from_layers(mdl, layers=['nset_left', 'nset_right', 'nset_middle'])

# Materials

mdl.add(ElasticIsotropic(name='mat_elastic', E=75*10**9, v=0.3, p=2700))

# Sections

mdl.add(ShellSection(name='sec_plate', t=0.001))

# Properties

mdl.add(Properties(name='ep_plate', material='mat_elastic', section='sec_plate', elset='elset_mesh'))

# Displacements

mdl.add([
    PinnedDisplacement(name='disp_left', nodes='nset_left'),
    RollerDisplacementX(name='disp_right', nodes='nset_right'),
    GeneralDisplacement(name='disp_middle', nodes='nset_middle', z=0.200),
])

# Loads

mdl.add(GravityLoad(name='load_gravity', elements='elset_mesh'))

# Steps

mdl.add([
    GeneralStep(name='step_bc', displacements=['disp_left', 'disp_right'], nlgeom=False),
    GeneralStep(name='step_loads', loads=['load_gravity'], displacements=['disp_middle'], nlgeom=False),
])
mdl.steps_order = ['step_bc', 'step_loads']

# Summary

mdl.summary()

# Run

mdl.analyse_and_extract(software='abaqus', fields=['u'])

rhino.plot_data(mdl, step='step_loads', field='um')
#rhino.plot_data(mdl, step='step_loads', field='smises')
`

**Comment by brgcode** [comment]
seems that RPC is unable to load some of the libraries needed by `numpy`. there can be many reasons for this depending on how `compas_fea` was installed.

from the error message i get the impression that `compas_fea` is installed in the `base` environment of Anaconda. is that correct?

**Comment by Beberger** [comment]
Thank you for the fast answer. compas seems to be installed in the base...
![image](https://user-images.githubusercontent.com/92813196/142400080-e73eb24c-6212-4381-a3f2-556e98ce7460.png)

I downloaded the zip of compas fea and unziped it, in the extended system properties I created a new environment variable to the path of src:
![image](https://user-images.githubusercontent.com/92813196/142401232-1ff71f18-084c-417b-ab88-b7d7c9efeff3.png)

When I check compas fea shoud be installed:
![image](https://user-images.githubusercontent.com/92813196/142401503-17cbf275-0080-4028-a48e-75e93eb99bd0.png)



when I run the script, a .inp file is created in the C/Temp path...
![image](https://user-images.githubusercontent.com/92813196/142401632-f7569d4e-57ef-4871-b5c8-6a59a547e949.png)

**Comment by brgcode** [comment]
this is not the way the package should be installed, but that is not your fault, because i noticed that the installation instructions are horribly outdated. the good news is that the problem is therefore easily fixed and will go away with a proper install.

i will update the instructions and ping you here as soon as they are available...

**Comment by Beberger** [comment]
ok, thank you.

**Comment by brgcode** [comment]
new instructions are available here
https://compas.dev/compas_fea/latest/gettingstarted/installation.html

let me know if you need more help to get this to work...

**Comment by Beberger** [comment]
Thank you. I was able to install it and it works now.
